### ISSUE TITLE
Verificación de la correcta creación de la wiki en español/ingles

### ISSUE THREAD

**Issue by nuhazet6** [desiresa/proyecto-ets-daw#10]

**Comment by diegxalv** [comment]
- Se completa la creación de las páginas de la Wiki, tanto en español como en inglés. 
- Se finaliza el índice derecho de la Wiki, separando en dos secciones cada idioma, eliminando así el índice que contenía la página principal de la Home de la Wiki.
- Se verifican las rutas a las imágenes de los Diagramas creados, así mismo que todas las páginas estén traducidas.
- Se procede a resolver el issue #10.
